# Generated by Django 3.2.12 on 2022-03-27 21:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('file', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
            ],
        ),
    ]
