# Generated by Django 3.2.12 on 2022-03-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_form_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='user',
        ),
    ]
